#pragma once

#if __has_include("config.local.h")
#include "config.local.h"
#else
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SERVER_BASE_URL "http://127.0.0.1:8000"
#endif
#define DEVICE_NAME "Open AIO"
#define DEVICE_ID "cooler-display-01"
#define API_KEY "change-me"

#ifndef NZXT_ESC_TEST_FIRMWARE
#define NZXT_ESC_TEST_FIRMWARE 0
#endif
#ifndef SIGNALRGB_VIDEO_FAST_PATH
#define SIGNALRGB_VIDEO_FAST_PATH NZXT_ESC_TEST_FIRMWARE
#endif
#ifndef NZXT_CAM_SPOOF
#define NZXT_CAM_SPOOF 0
#endif

#ifndef NZXT_CAM_HID_ONLY
#define NZXT_CAM_HID_ONLY 0
#endif

#define DISPLAY_WIDTH 480
#define DISPLAY_HEIGHT 480
#if SIGNALRGB_VIDEO_FAST_PATH
#define DISPLAY_ROTATE_180 0
#else
#define DISPLAY_ROTATE_180 1
#endif
#define SIGNALRGB_FPS_OVERLAY 0
#ifndef HAS_LILYGO_PANEL_FRAMEBUFFER
#define HAS_LILYGO_PANEL_FRAMEBUFFER 0
#endif
#if SIGNALRGB_VIDEO_FAST_PATH
#define SIGNALRGB_DIRECT_FRAMEBUFFER 1
#else
#define SIGNALRGB_DIRECT_FRAMEBUFFER 0
#endif
#define SIGNALRGB_DIRECT_CACHE_WRITEBACK 0
#define SIGNALRGB_DIRECT_DECODE_OFFSCREEN 0
#if SIGNALRGB_VIDEO_FAST_PATH
#define SIGNALRGB_DIRECT_JPEG_FRAMEBUFFER_DECODE 1
#else
#define SIGNALRGB_DIRECT_JPEG_FRAMEBUFFER_DECODE 0
#endif
#define SIGNALRGB_DIRECT_FPS_OVERLAY 0
#ifndef SIGNALRGB_MIN_RENDER_INTERVAL_MS
#if SIGNALRGB_VIDEO_FAST_PATH
#define SIGNALRGB_MIN_RENDER_INTERVAL_MS 33
#else
#define SIGNALRGB_MIN_RENDER_INTERVAL_MS 50
#endif
#endif
#define ASSET_WIDTH 160
#define ASSET_HEIGHT 160
#define POLL_INTERVAL_MS 1000UL
#define MAX_ASSET_SIZE_BYTES 131072UL
#define SIGNALRGB_SERIAL_BAUD 4000000
