/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProtocolInfo {
  vid: number
  pid: number
  outEndpoint: number
  inEndpoint: number
  chunkSize: number
  jpegCommand: number
}
export interface UsbWriteResult {
  ok: boolean
  status: string
  error?: string
  bytes: number
  writeMs: number
}
export declare function protocolInfo(): ProtocolInfo
export declare function makeSignalrgbJpegHeader(jpeg: Buffer, scale?: number | undefined | null, waitStatus?: boolean | undefined | null): Buffer
export declare class OpenAioUsb {
  constructor()
  sendSignalrgbJpeg(jpeg: Buffer, scale?: number | undefined | null): UsbWriteResult
  close(): void
}
